version: "3"
services:

  golang:
    container_name: golang
    env_file:
      - ./backend/app/.env
    build:
      context: ./docker
      dockerfile: Dockerfile.backend
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./backend/app:/go/src/app
    command: sh -c 'go mod tidy && GO_ENV=dev air'
    networks:
      - network1

  db:
    container_name: postgres
    image: postgres
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      TZ: "Asia/Tokyo"
    restart: always
    networks:
      - network1

volumes:
  postgres_volume:
    name: postgres_volume

networks:
  network1:
    external: true
